zabbix_api_url: "http://localhost:80/api_jsonrpc.php"
zabbix_api_user: "Admin"
zabbix_api_pass: "zabbix"

zabbix_hosts:
  - host: "Mysql"
    dns: "zabbix-agent2"
    groups:
      - "Zabbix/Databases"
    templates:
      - "MySQL by Zabbix agent 2"
    macros:
      - macro: '{$MYSQL.DSN}'
        value: 'tcp://zabbix-mysql:3306'
      - macro: '{$MYSQL_USER}'
        value: 'zbx_monitor'
      - macro: '{$MYSQL_PASSWORD}'
        value: 'P@ssw0rd#001'

zabbix_hostgroups:
  - Zabbix/Databases
  - Zabbix/Server
  - Zabbix/Docker
  - Zabbix/Frontend
  - Zabbix/GLPi

custom_template_name: Zabbix Frontend Http
custom_template_file: roles/zabbix/files/ZabbixFrontendHttp.yml