- name: Criar diretório /opt/zabbix/web
  file:
    path: /opt/zabbix/web
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Subir stack Zabbix com Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ stack_base_dir }}/zabbix"

- name: Aguardar Zabbix iniciar
  wait_for:
    port: 8080
    host: "localhost"
    timeout: 60