- name: Criar diretório de destino para stack do Zabbix
  file:
    path: /opt/zabbix
    state: directory
    mode: '0755'

- name: Copiar stack do Zabbix para /opt/
  copy:
    src: /vagrant/stacks/zabbix/
    dest: /opt/zabbix/
    remote_src: yes

- name: Subir containers Zabbix
  command: docker compose up -d
  args:
    chdir: /opt/zabbix/    