#version: '3'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  monitoring-net:
    external: true
    name: zabbix_monitoring-net
