- name: Verificar se a rede Docker 'monitoring-net' existe
  community.docker.docker_network_info:
    name: monitoring-net
  register: docker_network_result
  failed_when: false

- name: Criar a rede Docker 'monitoring-net' caso não exista
  community.docker.docker_network:
    name: monitoring-net
    state: present
    driver: bridge
  when: not docker_network_result.exists