- name: Verificar se a rede Docker 'zabbix_monitoring-net' já existe
  shell: docker network ls --filter name=^zabbix_monitoring-net$ --format "{{ '{{' }} .Name {{ '}}' }}"
  register: docker_network_check
  changed_when: false

- name: Criar a rede Docker 'zabbix_monitoring-net' se não existir
  shell: |
    docker network create \
      --driver bridge \
      --subnet 172.25.0.0/28 \
      --gateway 172.25.0.1 \
      zabbix_monitoring-net
  when: docker_network_check.stdout != "zabbix_monitoring-net"
