apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    isDefault: true
    url: http://zabbix-web:8080/api_jsonrpc.php
    jsonData:
      username: Admin
    secureJsonData:
      password: zabbix