version: '3'

services:
  mysql:
    image: mysql:8.0 # Use the latest Mysql image
    container_name: mysql-server # Set the container name
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_bin
      - --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql # Persist MySql data
    restart: unless-stopped

volumes:
  mysql-storage:
